all:
	dot -Tps vfio-migration-state-machine.dot -o vfio-migration-state-machine.pdf
png:
	dot -Tpng vfio-migration-state-machine.dot -o vfio-migration-state-machine.png
clean:
	rm -fr vfio-migration-state-machine.pdf
